version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Messaging port
      - "15672:15672"    # Management UI port

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:80"   
    depends_on:
      - api
