apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: zuul-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: <API_IMAGE_NAME>   # Replace with the correct API Docker image
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017"
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: zuul-core
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
