apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: zuul-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672   # Message Queue port ... i'm listening
            - containerPort: 15672  # Management Console port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: zuul-core
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
    - port: 15672
      targetPort: 15672
  type: ClusterIP
